### ISSUE TITLE
Balance doesn't match amount of DEVV tokens

### ISSUE THREAD

**Issue by maxcassano** [DevvioInc/Devv-Core#19]
**Describe the bug**
DEVV balance in SEND page doesn't match balance in History

**To Reproduce**
1. Go to REQUEST
2. Click on Request
3. CLick on Request
4. CLick on Request

Total balance is 300 Devv

5. Click on SEND

Total balance displayed is 200 DEVV

6. CLick on REFRESH

Total balance is still 200 DEVV

**Expected behavior**
Total Balance should be 300 DEVV

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 7

**Comment by spmckenney** [comment]
Has this been resolved in release v0.2.2?

**Comment by maxcassano** [comment]
solved, couldn't replicate same error in 2.2
